name: masr_spaces_backend
description: Backend API for Masr Spaces platform.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  supabase: ^0.2.8
  dotenv: ^3.1.0
  uuid: ^3.0.7
  json_annotation: ^4.8.0
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.6.1